@php
    $dueLabel = $task->due_date?->translatedFormat('d M Y') ?? 'Tanpa deadline';
@endphp
<article class="task-card {{ $task->status === 'done' ? 'is-done' : '' }}" draggable="{{ $view === 'board' ? 'true' : 'false' }}" data-drag-task="{{ $task->id }}" data-status-url="{{ route('tasks.status', $task) }}">
    <form class="check-form" method="POST" action="{{ route('tasks.status', $task) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $task->status === 'done' ? 'todo' : 'done' }}"><button class="task-check {{ $task->status === 'done' ? 'checked' : '' }}" aria-label="{{ $task->status === 'done' ? 'Buka kembali' : 'Selesaikan' }} {{ $task->title }}">@if($task->status === 'done')<span aria-hidden="true">✓</span>@endif</button></form>
    <div class="task-main"><button class="task-title" type="button" data-edit-task="{{ $task->id }}">{{ $task->title }}</button><p class="task-desc">{{ $task->description ?: 'Belum ada deskripsi.' }}</p><div class="task-meta"><span class="due-label {{ $task->isOverdue() ? 'overdue' : '' }}"><x-icon name="calendar" size="13"/>{{ $dueLabel }}@if($task->isOverdue())<b> · Terlambat</b>@endif</span>@if($task->attachments->isNotEmpty())<span class="attachment-count">{{ $task->attachments->count() }} file</span>@endif</div>@if($task->attachments->isNotEmpty())<div class="attachment-list">@foreach($task->attachments as $attachment)<span class="attachment-pill"><a href="{{ route('attachments.download', $attachment) }}" title="Unduh {{ $attachment->original_name }}">{{ \Illuminate\Support\Str::limit($attachment->original_name, 22) }}</a><form method="POST" action="{{ route('attachments.destroy', $attachment) }}" data-confirm="Hapus lampiran {{ $attachment->original_name }}?">@csrf @method('DELETE')<button type="submit" aria-label="Hapus lampiran {{ $attachment->original_name }}">×</button></form></span>@endforeach</div>@endif</div>
    <a class="project-chip" href="{{ route('tasks.index', ['project_id' => $task->project_id]) }}"><span>{{ mb_strtoupper(mb_substr($task->project?->name ?? '?', 0, 1)) }}</span>{{ $task->project?->name ?? 'Tanpa proyek' }}</a>
    <form class="status-form" action="{{ route('tasks.status', $task) }}" method="POST">@csrf @method('PATCH')<select name="status" class="status-select status-{{ $task->status }}" aria-label="Status {{ $task->title }}" data-submit-change>@foreach(\App\Models\Task::STATUSES as $key => $label)<option value="{{ $key }}" @selected($task->status === $key)>{{ $label }}</option>@endforeach</select></form>
    <div class="task-actions"><button type="button" class="icon-btn" data-edit-task="{{ $task->id }}" aria-label="Edit {{ $task->title }}"><x-icon name="edit" size="16"/></button><button type="button" class="icon-btn danger" data-delete-task="{{ $task->id }}" aria-label="Hapus {{ $task->title }}"><x-icon name="delete" size="16"/></button></div>
</article>
